drop table if exists rfc_call_history;

CREATE TABLE `rfc_call_history` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`ENVIRONMENT`	TEXT,
	`CHAIN_AUTO_FIX`	TEXT,
	`LOG_ID`	TEXT,
	`CHAIN_ID`	TEXT,
	`CHAIN_TEXT`	TEXT,
	`TYPE`	TEXT,
	`VARIANTE`	TEXT,
	`VARIANTE_TEXT`	TEXT,
	`INSTANCE`	TEXT,
	`JOB_COUNT`	TEXT,
	`ACTUAL_STATE`	TEXT,
	`ACTIVE_TIME`	INTEGER,
	`BATCHDATE`	TEXT,
	`BATCHTIME`	TEXT,
	`SUGGEST_ACTION`	TEXT,
	`FAILED_TIMES`	INTEGER,
	`FIX_DATE`	TEXT,
	`FIX_TIME`	TEXT,
	`FIX_ACTION`	TEXT,
	`ERROR_KEY_WORD`	TEXT,
	`STATUS`	TEXT,
	`RETURN_MSG`	TEXT,
	`IP`	NUMERIC
);